# Generated by Django 2.2.11 on 2020-03-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userreg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
