# Generated by Django 2.2.11 on 2020-03-06 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userreg', '0002_reg_age'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reg',
            new_name='UserReg',
        ),
    ]
