# Generated by Django 2.2.11 on 2020-03-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userreg', '0003_auto_20200306_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='city',
            field=models.CharField(max_length=10),
        ),
    ]
